---
# Common role variables

# General app config
app_name: "My App"
app_version: "1.0"
app_env: "development"

# Database config
db_host: "localhost"
db_name: "my_app_db_dev"
db_user: "my_app_user_dev"
db_password: "my_app_password_dev"

# Other config
debug: false
log_level: "debug"