---
- name: Install PHP and required modules
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - php
      - php-fpm
      - php-mysql
      - php-mbstring
      - php-xml
      - php-zip

- name: Install Composer
  become: yes
  command: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

- name: Copy Laravel application files
  become: yes
  synchronize:
    src: /path/to/laravel/app
    dest: /var/www/laravel
    remote_src: yes

- name: Run Composer install
  become: yes
  command: composer install --no-dev -d /var/www/laravel

- name: Create .env file
  become: yes
  copy:
    src: /path/to/laravel/.env
    dest: /var/www/laravel/.env

- name: Generate Laravel application key
  become: yes
  command: php /var/www/laravel/artisan key:generate

- name: Configure PHP-FPM
  become: yes
  template:
    src: /path/to/php-fpm config.template
    dest: /etc/php/7.4/fpm/pool.d/www.conf
    owner: root
    group: root
    mode: 0644

- name: Restart PHP-FPM service
  become: yes
  service:
    name: php7.4-fpm
    state: restarted

- name: Configure web server
  become: yes
  template:
    src: /path/to/web-server.template
    dest: /etc/nginx/sites-available/laravel
    owner: root
    group: root
    mode: 0644

- name: Create symlink for web server
  become: yes
  file:
    src: /etc/nginx/sites-available/laravel
    dest: /etc/nginx/sites-enabled/laravel
    state: link

- name: Restart web server service
  become: yes
  service:
    name: nginx
    state: restarted


