name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ssh-key && chmod 600 ssh-key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to production
      run: |
        ssh-keyscan -t rsa $DEPLOY_HOST >> ~/.ssh/known_hosts
        ssh -i ssh-key $DEPLOY_USER@$DEPLOY_HOST 'bash -s' < scripts/deploy.sh
      env:
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
