name: CI

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ secrets.AWS_REGION }} > ~/.aws/credentials
    
    - name: Terraform Init
      run: terraform init -backend-config=backend.tf
      
    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars
      
    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=terraform.tfvars
      
  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Ansible Install
      run: sudo apt-add-repository --yes --update ppa:ansible/ansible
      run: sudo apt-get install ansible
      
    - name: Ansible Deploy
      run: ansible-playbook ansible/main.yml
